import os
import argparse
import pandas as pd
from torch.utils.tensorboard import SummaryWriter

def convert_csv_to_tensorboard(csv_path, log_dir):
    """
    Reads a CSV file generated by Stable Baselines 3 or custom loggers
    and writes the data to a TensorBoard log directory.
    """
    if not os.path.exists(csv_path):
        print(f"Error: CSV file not found at {csv_path}")
        return

    print(f"Reading data from {csv_path}...")
    try:
        df = pd.read_csv(csv_path)
    except Exception as e:
        print(f"Error reading CSV: {e}")
        return

    # Create the log directory if it doesn't exist
    os.makedirs(log_dir, exist_ok=True)
    
    # Initialize TensorBoard writer
    writer = SummaryWriter(log_dir=log_dir)

    # Use 'time/total_timesteps' as the global step if available, otherwise just use the row index
    if 'time/total_timesteps' in df.columns:
        steps = df['time/total_timesteps'].values
    else:
        steps = df.index.values

    print(f"Found {len(df)} rows. Writing to TensorBoard...")

    for i, step in enumerate(steps):
        row = df.iloc[i]
        for col in df.columns:
            # Skip the step column itself or any non-numeric columns
            if col == 'time/total_timesteps' or pd.isna(row[col]):
                continue
            
            try:
                val = float(row[col])
                writer.add_scalar(col, val, global_step=int(step))
            except (ValueError, TypeError):
                # Skip non-numeric data
                pass

    writer.close()
    print(f"Successfully wrote TensorBoard logs to {log_dir}")
    print(f"Run the following command to view the graphs:")
    print(f"    tensorboard --logdir \"{log_dir}\" --port 6006")

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="Convert CSV metrics to TensorBoard logs")
    parser.add_argument("csv_path", type=str, help="Path to the input CSV file")
    parser.add_argument("--log_dir", type=str, default="logs/imported_tb", help="Path to output TensorBoard directory")
    
    args = parser.parse_args()
    convert_csv_to_tensorboard(args.csv_path, args.log_dir)
